theme = "ghd"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
mouse = false
scrolloff = 10
color-modes = true
rulers = []
auto-completion = true
auto-save = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab= "-"
tabpad = "-"

[editor.indent-guides]
render = false
character = "╎"
skip-levels = 2

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "file-name"]
right = ["diagnostics", "selections", "position-percentage", "position", "total-line-numbers", "file-encoding", "file-type"]
separator = "│"

[keys.normal]
Y = ["yank_main_selection_to_clipboard"]
0 = ["goto_line_start"]
G = ["goto_last_line"]
X = ["extend_line_above"]
F = ":format"

# Arrow keys nav in split-window mode
left = ["jump_view_left"]
down = ["jump_view_down"]
up = ["jump_view_up"]
right = ["jump_view_right"]

# close a split-window
C-q = ["wclose"]

[keys.normal.backspace]
r = [":run-shell-command sh ~/.config/helix/set-ruler.sh", ":config-reload"]
D = ":insert-output date"
p = ":insert-output pwgen -cnys 35 1"
c = ["kill_to_line_end", "insert_mode"]
d = ["kill_to_line_end"]
l = ":insert-output python3 ~/.config/helix/ipsum.py"
s = [":run-shell-command sh ~/.config/helix/auto-save.sh", ":config-reload"]
i = [":run-shell-command sh ~/.config/helix/indent-guides.sh", ":config-reload"]

[keys.normal.backspace.t]
p = [":insert-output cat ~/.config/helix/template.python", ":set-language python"]
c = [":insert-output cat ~/.config/helix/template.clang", ":set-language c"]

[keys.normal.g]
q = [":reflow 80", "goto_line_start"]

[keys.insert]

[keys.select]
Y = ["yank_main_selection_to_clipboard"]
